#!/bin/sh
# Install the per-run keys generated by demo/demo.sh, then run sshd.
# The client key is authorized with `restrict`: no pty, no forwarding. The
# verifier only ever needs `sh -s` reading a script from stdin.
set -eu
install -m 600 /keys/host_ed25519 /etc/ssh/ssh_host_ed25519_key
install -d -m 700 -o drift -g drift /home/drift/.ssh
printf 'restrict %s\n' "$(cat /keys/client.pub)" >/home/drift/.ssh/authorized_keys
chown drift:drift /home/drift/.ssh/authorized_keys
chmod 600 /home/drift/.ssh/authorized_keys
exec /usr/sbin/sshd -D -e
